version: "3.8"
services:
  nuxeo:
    image: nuxeo-wavefront-obj-converter:2021.1.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
      - NUXEO_DEV=true
      - NUXEO_CLID=${NUXEO_CLID}
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
volumes:
  data: {}
